spring:
  application:
    name: tao-ai-code-mother
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tao_ai_code_mother
    username: root
    password: 12345678
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.tao.taoaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn